apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: my-image-1
        image: pluralsightacrsp.azurecr.io/dockerapp:#{Build.BuildId}#
        ports:
        - containerPort: 80
